# File definisi lingkungan Conda
# Digunakan oleh MLflow untuk mereplikasi lingkungan training

name: mlflow-tensorflow-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip
  - mlflow==2.10.2
  - dagshub
  - gunicorn
  - numpy
  - scikit-learn
  - pip:
      # Tensorflow seringkali lebih stabil diinstal via pip
      - tensorflow
