# File definisi lingkungan Conda
# Digunakan oleh MLflow untuk mereplikasi lingkungan training

name: mlflow-tensorflow-env
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip
  # KUNCI UTAMA: "Kunci" versi MLflow ke versi yang stabil dan kompatibel
  - mlflow==2.10.2
  - numpy
  - scikit-learn
  - pip:
      # Tensorflow seringkali lebih stabil diinstal via pip
      - tensorflow
